export const faFacebook: IconDefinition;
export const faFacebookF: IconDefinition;
export const faFacebookSquare: IconDefinition;
export const faInstagram: IconDefinition;
export const faLinkedin: IconDefinition;
export const faLinkedinIn: IconDefinition;
export const faYoutube: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const fab: IconPack;