export const faArrowDown: IconDefinition;
export const faArrowLeft: IconDefinition;
export const faArrowRight: IconDefinition;
export const faArrowUp: IconDefinition;
export const faEnvelope: IconDefinition;
export const faLongArrowAltDown: IconDefinition;
export const faLongArrowAltLeft: IconDefinition;
export const faLongArrowAltRight: IconDefinition;
export const faLongArrowAltUp: IconDefinition;
export const faLongArrowDown: IconDefinition;
export const faLongArrowLeft: IconDefinition;
export const faLongArrowRight: IconDefinition;
export const faLongArrowUp: IconDefinition;
export const faMinus: IconDefinition;
export const faPlus: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const far: IconPack;